# Generated by Django 3.0.3 on 2020-03-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='model',
            new_name='body',
        ),
    ]
